feat(#1): init project
VilnaCRM-Org/website pull request #2
Opened 2022-10-17 19:34 UTC by TuranC

2022-10-17 19:38 UTC, TuranC commented on tsconfig.json
> +    //    "incremental": true,
remove comments

2022-10-22 10:14 UTC, TuranC commented on package.json
> +    "@commitlint/config-conventional": "^17.1.0",
check task number and check message

2022-10-22 10:22 UTC, TuranC commented on .husky/pre-commit
> +pnpm lint
https://gist.github.com/seeliang/0f0de424d1cdc4541c338f4ee93b7e6a

add git --diff, to optimize lint perfomance

2022-10-22 10:27 UTC, TuranC commented on .husky/pre-commit
> +pnpm lint
add to the pre-push hook deepscan and auto tests execution

2022-10-22 10:34 UTC, vilnacrm commented
we need to add file .gitignore to all empty directories in the project to ensure that directories are shown in the repository for other developers

2022-10-22 10:56 UTC, TuranC commented
fix errors for pnpm install

2022-10-22 11:00 UTC, TuranC commented
check MSW, and is it working?

2022-10-22 11:02 UTC, TuranC commented
check all booletproof steps

2023-05-16 16:19 UTC, Kravalg requested changes
I think that we need to add a docker environment there using the make command like in the [php-service-template.](https://github.com/VilnaCRM-Org/php-service-template/blob/b1def46c86ae89e60a27a526d293a0b53b23c3d4/Makefile)
Then we need to update local and GitHub CI.

2023-05-27 23:13 UTC, Kravalg commented
> check MSW, and is it working?

We will introduce this in the next versions

2023-05-28 15:02 UTC, merged